#!/bin/bash

# ... fetching from Ensembl Genomes

HUMAN_ANNOTATION_GFF="ftp://ftp.ensembl.org/pub/release-98/gff3/homo_sapiens/Homo_sapiens.GRCh38.98.chr.gff3.gz"
HUMAN_ANNOTATION_GTF="ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.chr.gtf.gz"
HUMAN_ASSEMBLY="ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"

wget -O $(basename $HUMAN_ANNOTATION_GFF) $HUMAN_ANNOTATION_GFF
wget -O $(basename $HUMAN_ANNOTATION_GTF) $HUMAN_ANNOTATION_GTF
wget -O $(basename $HUMAN_ASSEMBLY)   $HUMAN_ASSEMBLY
gunzip Homo_sapiens.*gz

#rRNA gene sequences were were collected from GenBank and Ensembl and saved as
#file Hs_rRNA.fa (4 genes).
