#!/bin/bash

# ... fetching from Ensembl Genomes

HUMAN_ANNOTATION="ftp://ftp.ensembl.org/pub/release-98/gff3/homo_sapiens/Homo_sapiens.GRCh38.98.chr.gff3.gz"
HUMAN_ASSEMBLY="ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"

wget -O $(basename $HUMAN_ANNOTATION) $HUMAN_ANNOTATION
wget -O $(basename $HUMAN_ASSEMBLY)   $HUMAN_ASSEMBLY
gunzip Homo_sapiens.*gz

#rRNA coding regions were collect from Ensembl Biomart using the following query:
#
#http://useast.ensembl.org/biomart/martview/fafb897cbd4b36b571d79261e13f0be9?VIRTUALSCHEMANAME=default&ATTRIBUTES=hsapiens_gene_ensembl.default.sequences.ensembl_gene_id|hsapiens_gene_ensembl.default.sequences.ensembl_gene_id_version|hsapiens_gene_ensembl.default.sequences.ensembl_transcript_id|hsapiens_gene_ensembl.default.sequences.ensembl_transcript_id_version|hsapiens_gene_ensembl.default.sequences.gene_exon_intron&FILTERS=hsapiens_gene_ensembl.default.filters.biotype."rRNA"&VISIBLEPANEL=resultspanel
#
#and saved as file Hs_grRNA.fa (76 genes).
